### ISSUE TITLE
App crashing on Meteor.com hosting

### ISSUE THREAD

**Issue by benstr** [meteor-vegas/website#42]
Hey team! Great work on this project. I see vegas.meteor.com is crashing just like our chicago.meteor.com is crashing. Running the app in production mode locally works fine. Our logs:

```
[Tue Sep 15 2015 00:57:52 GMT+0000 (UTC)] INFO STATUS waiting -> starting
[Tue Sep 15 2015 00:57:52 GMT+0000 (UTC)] NOTICE Starting application on port 24974
[Tue Sep 15 2015 00:57:52 GMT+0000 (UTC)] INFO STATUS starting -> running
[Tue Sep 15 2015 00:57:58 GMT+0000 (UTC)] INFO setting timer for:  Tue Sep 15 2015 01:30:00 GMT+0000 (UTC)
[Tue Sep 15 2015 00:57:58 GMT+0000 (UTC)] INFO setting timer for:  Tue Sep 15 2015 01:30:00 GMT+0000 (UTC)
[Tue Sep 15 2015 00:57:58 GMT+0000 (UTC)] INFO ## Running Production Environment ##
[Tue Sep 15 2015 00:57:58 GMT+0000 (UTC)] INFO Fetching Meetup Member Profiles offset 0
[Tue Sep 15 2015 00:57:58 GMT+0000 (UTC)] WARNING 
undefined:1
<!DOCTYPE html>
^
SyntaxError: Unexpected token <
at Object.parse (native)
at /meteor/containers/00f85ad9-f070-89f0-8524-1b47e4a4896f/bundle/programs/server/npm/npm-container/node_modules/meetup-api/lib/meetup.js:80:42
at Request.callback (/meteor/containers/00f85ad9-f070-89f0-8524-1b47e4a4896f/bundle/programs/server/npm/npm-container/node_modules/meetup-api/node_modules/superagent/lib/node/index.js:519:3)
at Request.<anonymous>
(/meteor/containers/00f85ad9-f070-89f0-8524-1b47e4a4896f/bundle/programs/server/npm/npm-container/node_modules/meetup-api/node_modules/superagent/lib/node/index.js:133:10)
at Request.emit (events.js:95:17)
at IncomingMessage.<anonymous>
(/meteor/containers/00f85ad9-f070-89f0-8524-1b47e4a4896f/bundle/programs/server/npm/npm-container/node_modules/meetup-api/node_modules/superagent/lib/node/index.js:636:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:944:16
at process._tickCallback (node.js:442:13)
[Tue Sep 15 2015 00:57:58 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Tue Sep 15 2015 00:57:58 GMT+0000 (UTC)] ERROR Application crashed with code: 8
```

**Comment by mdijoux** [comment]
I had the same issue for Meteor-Reunion meetup. The error was that the IP address is banned by Cloudflare and api.meetup.com

**Comment by pcuci** [comment]
:+1: for montreal.meteor.com - any clue @Cram974 on how you worked around the issue?

I could `mup deploy` to some other server if necessary, people were active on our site
